In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
transports = pd.read_csv('transports.csv')
bus_stops = pd.read_csv('bus_stops.csv')
transports = transports.rename(columns={'District.Name': 'District_Name'})
bus_stops = bus_stops.rename(columns={'District.Name': 'District_Name'})

In [5]:
transports

,Code,Transport,Longitude,Latitude,Station,District_Name,Neighborhood.Name
0,K001,Underground,2.119370,41.399203,FGC (L6) - REINA ELISENDA (Sortida Duquesa d'O...,Sarrià-Sant Gervasi,Sarrià
1,K001,Underground,2.135427,41.397791,FGC (L6) - LA BONANOVA-,Sarrià-Sant Gervasi,Sant Gervasi - Galvany
2,K001,Underground,2.185391,41.451492,METRO (L11) - CASA DE L'AIGUA (C. Vila-Real)-,Nou Barris,la Trinitat Nova
3,K001,Underground,2.174473,41.460889,METRO (L11) - CIUTAT MERIDIANA (C. Pedraforca)-,Nou Barris,Ciutat Meridiana
4,K001,Underground,2.168588,41.387200,METRO (L1) - CATALUNYA (Rda. Universitat)-,Eixample,la Dreta de l'Eixample
...,...,...,...,...,...,...,...
646,K002,Railway (FGC),2.118998,41.398967,FGC - REINA ELISENDA-,Sarrià-Sant Gervasi,Sarrià
647,K008,Maritime station,2.175248,41.352808,Terminal Marítima E *Creuers,Sants-Montjuïc,la Marina del Prat Vermell
648,K008,Maritime station,2.174767,41.350955,Terminal Marítima D *Creuers,Sants-Montjuïc,la Marina del Prat Vermell
649,K002,Railway (FGC),2.131188,41.397617,FGC - LES TRES TORRES<center>-,Sarrià-Sant Gervasi,les Tres Torres
650,K001,Underground,2.158822,41.375220,METRO (L3) - POBLE SEC (C. de Manso)-,Eixample,Sant Antoni

In [6]:
bus_stops

,Code,Transport,Longitude,Latitude,Bus.Stop,District_Name,Neighborhood.Name
0,K014,Day bus stop,2.171619,41.413744,BUS -192--,Horta-Guinardó,el Guinardó
1,K014,Day bus stop,2.134902,41.420222,BUS -124--,Gràcia,Vallcarca i els Penitents
2,K014,Day bus stop,2.162913,41.423187,BUS -117--,Horta-Guinardó,la Font d'en Fargues
3,K014,Day bus stop,2.163667,41.422899,BUS -117--,Horta-Guinardó,la Font d'en Fargues
4,K014,Day bus stop,2.120212,41.397209,BUS -130--,Sarrià-Sant Gervasi,Sarrià
...,...,...,...,...,...,...,...
3157,K014,Day bus stop,2.183887,41.422024,BUS -191--,Sant Andreu,el Congrés i els Indians
3158,K014,Day bus stop,2.176710,41.446419,BUS -127-81--,Nou Barris,les Roquetes
3159,K015,Night bus stop,2.144596,41.411446,NITBUS -N4--,Gràcia,Vallcarca i els Penitents
3160,K014,Day bus stop,2.142256,41.371176,BUS -91-115-V5--,Sants-Montjuïc,la Bordeta
3161,K015,Night bus stop,2.134932,41.398495,NITBUS -N7--,Sarrià-Sant Gervasi,Sant Gervasi - Galvany

In [41]:
transportsD = transports.groupby(by=['District_Name']).count().sort_values(by=['Code'],ascending=False)
transportsD

,Code,Transport,Longitude,Latitude,Station,Neighborhood.Name
District_Name,,,,,,
Eixample,120,120,120,120,120,120
Sant Martí,70,70,70,70,70,70
Sarrià-Sant Gervasi,66,66,66,66,66,66
Sants-Montjuïc,53,53,53,53,53,53
Sant Andreu,40,40,40,40,40,40
Nou Barris,39,39,39,39,39,39
Horta-Guinardó,31,31,31,31,31,31
Ciutat Vella,27,27,27,27,27,27
Les Corts,24,24,24,24,24,24
Gràcia,17,17,17,17,17,17

In [42]:
bus_stopsD = bus_stops.groupby(by=['District_Name']).count().sort_values(by=['Code'],ascending=False)
bus_stopsD

,Code,Transport,Longitude,Latitude,Bus.Stop,Neighborhood.Name
District_Name,,,,,,
Sarrià-Sant Gervasi,439,439,439,439,439,439
Sants-Montjuïc,415,415,415,415,415,415
Eixample,405,405,405,405,405,405
Horta-Guinardó,389,389,389,389,389,389
Sant Martí,356,356,356,356,356,356
Nou Barris,330,330,330,330,330,330
Sant Andreu,228,228,228,228,228,228
Gràcia,210,210,210,210,210,210
Les Corts,207,207,207,207,207,207
Ciutat Vella,167,167,167,167,167,167

In [43]:
transportE = transports.query('District_Name == "Eixample"')
bus_stopsE = bus_stops.query('District_Name == "Eixample"')

In [134]:
Code_bus = bus_stops[['Transport','Code']].groupby('Code')["Transport"].value_counts().to_frame()
Code_bus["Bus_Number"] = Code_bus["Transport"]
Code_bus = Code_bus.drop('Transport', axis='columns')
Code_bus

                       Bus_Number
Code Transport
K014 Day bus stop            2324
K015 Night bus stop           828
K016 Airport bus stop           7
K017 Bus station                3

In [156]:
Code_transport = transportE[['Transport','Code']].groupby('Code')['Transport'].value_counts().to_frame()
Code_transport["Transp_Number"] = Code_transport["Transport"] 
Code_transport = Code_transport.drop('Transport', axis='columns')
Code_transport

                    Transp_Number
Code Transport
K001 Underground              103
K002 Railway (FGC)              7
K003 RENFE                      8
K004 Airport train              1
K011 Tram                       1

In [158]:
Transport_Eixamples = pd.concat([Code_bus, Code_transport], axis=1)
Transport_Eixamples = Transport_Eixamples['Bus_Number'].fillna(Transport_Eixamples['Transp_Number']).to_frame()
Transport_Eixamples = Transport_Eixamples.rename(columns={'Bus_Number':'Number of stops'})
Transport_Eixamples

                       Number of stops
Code Transport
K001 Underground                 103.0
K002 Railway (FGC)                 7.0
K003 RENFE                         8.0
K004 Airport train                 1.0
K011 Tram                          1.0
K014 Day bus stop               2324.0
K015 Night bus stop              828.0
K016 Airport bus stop              7.0
K017 Bus station                   3.0

In [159]:
bus_Stop = pd.concat([Transport_Eixamples.loc["K014"], Transport_Eixamples.loc["K015"]], axis=0)
bus_Stop

                Number of stops
Transport
Day bus stop             2324.0
Night bus stop            828.0